FROM python:latest
WORKDIR /web
ADD . /web
RUN pip install -r requirements.txt
# RUN rm -rf lib
# RUN git clone https://github.com/garrettmk/amazonmws lib/amazonmws
# RUN git clone https://github.com/garrettmk/xmallow lib/xmallow
RUN apt-get update && apt-get install -y supervisor
ENV PYTHONUNBUFFERED=1 PYTHONPATH=/web/lib/amazonmws:/web/lib/xmallow:/web/lib/sqlalchemy-jsonbase FLASK_APP=colander2.py
CMD ["supervisord", "-c", "supervisord_web.conf"]